import React, { createContext, useContext, useState, useEffect } from 'react';
import client from '../api/client';

const AuthContext = createContext(null);
const BROWSER_ID_KEY = 'scienceToppersBrowserId';

function getBrowserId() {
  let id = localStorage.getItem(BROWSER_ID_KEY);
  if (!/^[a-f0-9]{32}$/.test(id || '')) {
    const bytes = new Uint8Array(16);
    window.crypto.getRandomValues(bytes);
    id = Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
    localStorage.setItem(BROWSER_ID_KEY, id);
  }
  return id;
}

// Decode a JWT payload without verifying the signature (client-side display only)
function parseJwt(token) {
  try {
    const payload = token.split('.')[1];
    const decoded = JSON.parse(atob(payload.replace(/-/g, '+').replace(/_/g, '/')));
    return decoded;
  } catch {
    return null;
  }
}

export const AuthProvider = ({ children }) => {
  const [user, setUser]     = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = sessionStorage.getItem('token');
    if (token) {
      const claims = parseJwt(token);
      if (claims) {
        // JWT claims generated by JwtUtil: sub=username, role=STUDENT|ADMIN, owner=subject(optional)
        const tokenRole = claims.role || (claims.sub === 'admin' ? 'ADMIN' : 'STUDENT');
        const isSuperAdmin = tokenRole === 'SUPER_ADMIN';
        const role = isSuperAdmin ? 'ADMIN' : tokenRole;
        setUser({
          username:        claims.sub,
          role,
          uid:             claims.uid || claims.sub,
          owner:           claims.owner || null,
          isSuperAdmin,
          profileComplete: role === 'ADMIN' ? true : (claims.profileComplete !== false),
        });
      }
    }
    setLoading(false);
  }, []);

  const login = async (username, password, registerBrowser = false) => {
    try {
      const res = await client.post('/auth/login', {
        username,
        password,
        browserId: getBrowserId(),
        registerBrowser,
      });
      const token = res.data.token;
      sessionStorage.setItem('token', token);
      const claims = parseJwt(token);
      const tokenRole = claims?.role || (username === 'admin' ? 'ADMIN' : 'STUDENT');
      const isSuperAdmin = tokenRole === 'SUPER_ADMIN';
      const role = isSuperAdmin ? 'ADMIN' : tokenRole;
      setUser({
        username:        claims?.sub || username,
        role,
        uid:             claims?.uid || claims?.sub || username,
        owner:           claims?.owner || null,
        isSuperAdmin,
        // profileComplete comes from JWT claim if present, otherwise fetch separately
        profileComplete: role === 'ADMIN' ? true : (claims?.profileComplete !== false),
      });

      // If student, fetch their actual profileComplete status from Firebase
      if (role !== 'ADMIN') {
        try {
          const profileRes = await client.get('/auth/profile');
          const pc = profileRes.data?.profileComplete;
          setUser(prev => ({
            ...prev,
            profileComplete: pc === undefined ? true : Boolean(pc),
          }));
        } catch {
          // Silently ignore — default to true to not block existing users
        }
      }

      return { ok: true };
    } catch (e) {
      console.error('Login failed:', e);
      return {
        ok: false,
        code: e.response?.data?.code || 'LOGIN_FAILED',
        message: e.response?.data?.error || '',
      };
    }
  };

  const logout = async () => {
    try {
      await client.post('/auth/logout');
    } catch {
      // Local logout must still complete if the audit database is unavailable.
    } finally {
      sessionStorage.removeItem('token');
      setUser(null);
    }
  };

  // Called after the first-login modal is completed
  const markProfileComplete = () => {
    setUser(prev => prev ? { ...prev, profileComplete: true } : prev);
  };

  return (
    <AuthContext.Provider value={{ user, login, logout, loading, markProfileComplete }}>
      {!loading && children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => useContext(AuthContext);
