import React, { createContext, useContext, useState, useEffect } from 'react';
import client from '../api/client';

const AuthContext = createContext(null);

// Decode a JWT payload without verifying the signature (client-side display only)
function parseJwt(token) {
  try {
    const payload = token.split('.')[1];
    const decoded = JSON.parse(atob(payload.replace(/-/g, '+').replace(/_/g, '/')));
    return decoded;
  } catch {
    return null;
  }
}

export const AuthProvider = ({ children }) => {
  const [user, setUser]     = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (token) {
      const claims = parseJwt(token);
      if (claims) {
        // JWT claims generated by JwtUtil: sub=username, role=STUDENT|ADMIN, owner=subject(optional)
        setUser({
          username: claims.sub,
          role:     claims.role || (claims.sub === 'admin' ? 'ADMIN' : 'STUDENT'),
          uid:      claims.uid || claims.sub,
          owner:    claims.owner || null,
        });
      }
    }
    setLoading(false);
  }, []);

  const login = async (username, password) => {
    try {
      const res = await client.post('/auth/login', { username, password });
      const token = res.data.token;
      localStorage.setItem('token', token);
      const claims = parseJwt(token);
      setUser({
        username: claims?.sub || username,
        role:     claims?.role || (username === 'admin' ? 'ADMIN' : 'STUDENT'),
        uid:      claims?.uid || claims?.sub || username,
        owner:    claims?.owner || null,
      });
      return true;
    } catch (e) {
      console.error('Login failed:', e);
      return false;
    }
  };

  const logout = () => {
    localStorage.removeItem('token');
    setUser(null);
  };

  return (
    <AuthContext.Provider value={{ user, login, logout, loading }}>
      {!loading && children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => useContext(AuthContext);
